name: json_ast
version: 1.0.6
author: Daniele Spyryto Zecchin <danielezecchin@gmail.com>
description: A library that builds the abstract syntax tree for a JSON string.
homepage: https://github.com/Spyryto/json_ast
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  grapheme_splitter:
    git:
      url: https://github.com/Spyryto/grapheme_splitter
      version: ^1.0.1

dev_dependencies:
  path: ^1.8.0
  pedantic: ^1.11.0
  test: ^1.17.5